# Generated by Django 4.1.5 on 2023-01-30 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("form", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="form",
            name="file",
            field=models.FileField(upload_to="txt/"),
        ),
    ]
