# Generated by Django 4.1.5 on 2023-01-30 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("form", "0002_alter_form_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="form",
            name="file",
            field=models.FileField(max_length=600, upload_to=""),
        ),
    ]
